all:

.PHONY: clean

clean:
	@rm -f *~ .gitignore~
	(cd anim/ && make clean)
	(cd cartoon/ && make clean)
	(cd refinemass/ && make clean)
	(cd agu/ && make clean)
	(cd liwg/ && make clean)
	(cd siamgs/ && make clean)
	(cd dms/ && make clean)

